kind: Deployment
apiVersion: apps/v1
metadata:
  name: fiap-aso7-app
  generation: 1
  namespace: fiap-7aso-grupo-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-aso7-app
  template:
    metadata:
      labels:
        app: fiap-aso7-app      
    spec:
      containers:
        - name: fiap-aso7-app
          image: image-registry.openshift-image-registry.svc:5000/fiap-7aso-grupo-8/fiap-7aso:latest
          ports:
            - containerPort: 8081
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
          env:
            - name: DATABASE_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: db-service-name
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: db-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: db-pass
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: db-name               
      restartPolicy: Always
