apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fiap-7aso
  namespace: fiap-7aso-grupo-8
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fiap-7aso
  namespace: fiap-7aso-grupo-8
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/cmedinadev/fiap-7aso-ocp.git'
    contextDir: /app
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:12-ubi7'
  output:
    to:
      kind: ImageStreamTag
      name: 'fiap-7aso:latest'
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange      
